# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
