# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'superhero',
                'ordering': ['-added_on'],
                'verbose_name_plural': 'superheroes',
            },
        ),
    ]
