# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0004_auto_20170119_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
