# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
